CREATE TABLE IF NOT EXISTS t_region (
  id BIGINT PRIMARY KEY,
  code VARCHAR(32) NOT NULL UNIQUE,
  name VARCHAR(64) NOT NULL,
  subtitle VARCHAR(128) NOT NULL,
  theme_color VARCHAR(16) NOT NULL,
  sort_order INT NOT NULL
);
CREATE TABLE IF NOT EXISTS t_location (
  id BIGINT PRIMARY KEY,
  region_code VARCHAR(32) NOT NULL,
  name VARCHAR(80) NOT NULL,
  category VARCHAR(32) NOT NULL,
  description VARCHAR(512) NOT NULL,
  image_url VARCHAR(1024) NOT NULL,
  score DECIMAL(3,1) NOT NULL,
  distance_km DECIMAL(6,1) NOT NULL,
  tags VARCHAR(255) NOT NULL,
  featured BOOLEAN NOT NULL DEFAULT FALSE
);
CREATE TABLE IF NOT EXISTS t_note (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  user_name VARCHAR(64) NOT NULL,
  avatar VARCHAR(255),
  location_name VARCHAR(80) NOT NULL,
  title VARCHAR(120) NOT NULL,
  content VARCHAR(1000) NOT NULL,
  image_url VARCHAR(1024),
  liked INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS t_supply_voucher (
  id BIGINT PRIMARY KEY,
  title VARCHAR(120) NOT NULL,
  location_name VARCHAR(80) NOT NULL,
  stock INT NOT NULL,
  total INT NOT NULL,
  end_at TIMESTAMP NOT NULL
);
CREATE TABLE IF NOT EXISTS t_supply_order (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT NOT NULL,
  voucher_id BIGINT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_order_user_voucher UNIQUE(user_id, voucher_id)
);

